### ISSUE TITLE
bugs when compile 

### ISSUE THREAD

**Issue by cuge1995** [ethnhe/FFB6D#14]
```
 Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake, version: 4.2.0
    /lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake, version: 4.2.0
```
I installed Opencv3 as your requirement.txt

**Comment by an99990** [comment]
I did what @ethnhe suggested and it still gives me the same error @cuge1995 has.

**Comment by ethnhe** [comment]
So it seems that the program can not find your installed opencv3 path correctly but use the opencv4 version 4.2, several ways that maybe will solve the problem.
- Modify this [line of code](https://github.com/hfutcgncas/normalSpeed/blob/2e734835ac861525952480561161385011a11f1b/normalSpeed/CMakeLists.txt#L10) to ```find_package(OpenCV 4 REQUIRED)``` to see if normalSpeed support OpenCV 4.
- Rather than using find_package to automatically find the required OpenCV package, define the OpenCV 3 path manually.
- The problem is caused by the previously installed OpenCV 4, uninstall OpenCV 4, and install OpenCV 3.

**Comment by an99990** [comment]
1- normalSpeed doesnt support opencv4
2- try to force path with find_package(OpenCV 3 EXACT REQUIRED PATHS ...) but still find opencv4
3- last solution didnt try yet.

**Comment by ghost** [comment]
Hey @an99990, have you managed to resolve your issue ? 

I'm facing exactly the same problem. Would really appreciate it to have your feedback on this.

**Comment by an99990** [comment]
i cant remember exactly im sorry, but i think i installed opencv with source and it somehow worked
